### PR TITLE
Allow installing on a Rails 5 app

### PR DESCRIPTION
**Pull request by adamico**

### CODE REVIEW

**Comment by ronen** [comment]
@adamico thanks for the PR.  Have you verified that schema_monkey doesn't work with rails 5?  (I haven't had a chance to look into it yet)

**Comment by ronen** [comment]
though re verifying that this doesn't work, the problem might be entirely with schema_plus_core; if that is the case, then the dependency here might not really need to change, possibly only the one in schema_plus_core as per your PR there

**Comment by theovoss** [comment]
I just tried using this in a Rails 5 app and I had to use @adamico's patches for schema_plus_views and schema_plus_core. Once I point at his branches, I can add views in my migration.

So my gemfile now looks like:
```
# TODO: once PR's merge, install from normal gem, not someone else's github repo.
gem "schema_plus_core", github: 'adamico/schema_plus_core', branch: 'patch-1'
gem "schema_plus_views", github: 'adamico/schema_plus_views', branch: 'patch-1'
```

Is there a timeline for Rails 5 support?

**Comment by ronen** [comment]
@theovoss thanks for posting.  Yes, simply changing the dependencies to allow loading AR 5 won't help since schema_plus_core hasn't been updated to handle AR 5.

> Is there a timeline and/or plan for Rails 5 support?

Unfortunately no specific timeline.  I don't have much time to spare at the moment; if/when I have a chance I'll of course take a look at it.  But it might not be for a few months.    (At the moment I'm not doing any active RoR development in my day jobs, so can't devote primary time for it.)

I'd be more than happy to accept PRs or collaborator requests if somebody else out there in github-land was motivated to dive in and git it working.  I don't actually think it'd be super hard.

**Comment by emptyflask** [comment]
SchemaPlus/schema_plus_core >= 2.0 supports Rails 5 now. Is there anything else in this repo that needs updating?

**Comment by boazy** [comment]
To make this work, we basically need to reconcile between the new built-in support for views in AR5 and what SchemaPlus::Views supported, and either choices may break apps relying on one or the other in subtle ways.

I think the best route is to follow AR5 here, and release a new major version, to avoid silently breaking apps. This means that we just remove the `connection.views` implementation and keep the `create_view` and `delete_view` which are still not provided by AR5.

That being said, looking at the differences between the SchemaPlus `connection.views` method and the AR5 one, they are rather small:

1. SP::Views accepts an extra argument (query name) while AR5's version has no args.
2. The queries used for the implementations of `connection.views` are slightly different for each database (e.g. "SHOW FULL TABLES" vs. "SELECT name FROM sqlite_master"). I think this only results in a difference for PostgreSQL, where AR5 would also return materialized views, but SP::Views would skip them.

@ronen what are your thoughts on the matter?

**Comment by ronen** [comment]
@boazy thanks for looking into the differences, and yes I agree.  

Whenever AR starts supporting something that SchemaPlus already does, but with different syntax or semantics, SchemaPlus should always switch to follow AR.

To make the transition easier, SchemaPlus could continue to support its old syntax but with a deprecation warning.  But in this case, the only deprecation would be the query name argument, which is easy enough for users to fix, so it doesn't seem to me to be worth the effort.

Between that and the fact that `connection.views()` would now support materialized views, this is a breaking change, so warrants a major version bump.

The only question I'd have is whether to retain support for AR4.2 in the new version.  For other SchemaPlus gems I've argued that we didn't need a version bump and could maintain support for both in a single major version.  But in this case, since we will be doing the version bump anyway I think there's no point continuing to support AR4.2 in the new version.  @boazy do you agree with that?

**Comment by boazy** [comment]
I've added full-fledged pull-request #16. Although it's not yet merge ready, it's closer to complete support and includes everything from this PR (basically just a dependency version change).

**Pull request closed without merging**
