### PR TITLE
Allow replace with views

### PR DESCRIPTION
**Pull request by hcarver**
Refactored as you suggested, added some documentation and tests. The instructions for setting up a dev environment didn't work for me, so I'm just crossing my fingers that the test passes!

### CODE REVIEW

**Comment by ronen** [comment]
@hcarver cool looks good.  Only one thing i might add to the doc is something along the lines of "subject to the some limitations; see the MySQL and PostgreSQL docs for details".  But no need to make you go back again, i'll just merge and then edit it myself.

> The instructions for setting up a dev environment didn't work for me

Bummer.  What didn't work?

>  so I'm just crossing my fingers that the test passes!

It does!

**Comment by ronen** [comment]
Actually I noticed that `:force` wasn't documented at all!  So I added documentation for both it and `:allow_replace` in the "Creating Views" section (moved your doc over).

I've release version 0.2.0 with this in it.  Thanks for your contribution!

**Comment by hcarver** [comment]
No problem!

I couldn't find a single set of instructions to follow, but I eventually realised I needed ruby 2.1.5, and to install the schema_dev gem (it wasn't installing under ruby 2.0.0, which is probably not a problem if development is intended to only be done on 2.1.5).

I can't remember exactly what the next error I had was, but I think it was around creating the databases needed.

**Comment by ronen** [comment]
> I eventually realized I needed... to install the schema_dev gem.

OK, yeah, that should be clearer.  And the README over there should give better setup instructions.  I've added an issue SchemaPlus/schema_dev#9

**Pull request merged**
